name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      with:
        static_site_generator: next
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linting
      run: npm run lint
      
    - name: Build with Next.js
      run: npm run build
      env:
        NODE_ENV: production
        
    - name: Verify build and add .nojekyll file
      run: |
        echo "Current directory contents:"
        ls -la
        echo "Checking for out directory..."
        if [ -d "out" ]; then
          echo "✓ out directory exists"
          ls -la out/ | head -5
        else
          echo "✗ out directory not found"
        fi
        echo "Creating .nojekyll file..."
        mkdir -p out
        touch out/.nojekyll
        echo "✓ .nojekyll file created"
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./out

  deploy:
    name: Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4